# Generated by Django 4.2.7 on 2025-09-20 16:13

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailySchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_schedules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "T_n",
                    models.DurationField(
                        help_text="Expected time needed to complete the task (hr/min/sec)"
                    ),
                ),
                (
                    "completed_so_far",
                    models.FloatField(
                        default=0.0,
                        help_text="Completion percentage (0-100%)",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ],
                    ),
                ),
                (
                    "delta",
                    models.IntegerField(
                        choices=[
                            (1, "Very Low"),
                            (2, "Low"),
                            (3, "Medium"),
                            (4, "High"),
                            (5, "Very High"),
                        ],
                        default=3,
                        help_text="Priority for the task",
                    ),
                ),
                ("due_date", models.DateField(help_text="Due date for the task")),
                ("due_time", models.TimeField(help_text="Due time for the task")),
                ("is_completed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["due_date", "due_time", "-delta"],
            },
        ),
        migrations.CreateModel(
            name="TaskAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "time_allotted",
                    models.DurationField(
                        help_text="Time allocated for this task today"
                    ),
                ),
                ("start_time", models.TimeField(help_text="Scheduled start time")),
                ("end_time", models.TimeField(help_text="Scheduled end time")),
                (
                    "completed_time",
                    models.DurationField(
                        blank=True, help_text="Actual time spent on task", null=True
                    ),
                ),
                ("is_completed", models.BooleanField(default=False)),
                (
                    "daily_schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_assignments",
                        to="study.dailyschedule",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="study.task"
                    ),
                ),
            ],
            options={
                "ordering": ["start_time"],
            },
        ),
    ]
