#!/bin/bash
# Setup guide for MongoDB Atlas

echo "================================"
echo "MongoDB Atlas Setup Guide"
echo "================================"
echo ""
echo "Follow these steps to set up MongoDB Atlas:"
echo ""
echo "1. Go to https://www.mongodb.com/cloud/atlas"
echo "2. Create a free account or log in"
echo "3. Create a new cluster (Free tier available)"
echo "4. Configure database access:"
echo "   - Click 'Database Access' in the sidebar"
echo "   - Add a new database user with password"
echo "   - Save the username and password"
echo "5. Configure network access:"
echo "   - Click 'Network Access' in the sidebar"
echo "   - Add IP Address: 0.0.0.0/0 (allows access from anywhere)"
echo "   - Or add your specific AWS region's IP range"
echo "6. Get your connection string:"
echo "   - Click 'Clusters' in the sidebar"
echo "   - Click 'Connect' on your cluster"
echo "   - Choose 'Connect your application'"
echo "   - Copy the connection string"
echo "   - Replace <password> with your database user password"
echo ""
echo "Example connection string:"
echo "mongodb+srv://username:password@cluster0.xxxxx.mongodb.net/?retryWrites=true&w=majority"
echo ""
echo "7. Set the connection string in your environment:"
echo "   eb setenv MONGODB_URI='your-connection-string-here'"
echo "   eb setenv MONGODB_NAME='studybunny'"
echo ""
echo "================================"

